name: MinigameFixes
version: @version@-@apiversion@
description: 'fix some issues with minigames'
authors: [mindw0rm]
website: https://github.com/mindw0rm/MinigameFixes
api-version: 1.15
depend: [BedWars]
main: net.kaoztribe.minigamefixes.MinigameFixes
permissions:
  minigames.keepInventory:
    default: op